# Import libraries
### Pandas, Sklearn, Numpy

In [1]:
import pandas as pd
import numpy as np
from numpy import absolute

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

from sklearn.linear_model import ElasticNet, Lasso, Ridge

# Load dataset and split into input/output

In [2]:
df = pd.read_excel("ENB2012_data.xlsx")
Y = df["Y2"]
X = df.drop("Y2", axis=1)
display(df)

       X1     X2     X3      X4   X5  X6   X7  X8     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.03

[768 rows x 9 columns]

# Perform 5-fold Cross Validation and score using MSE

In [3]:
cv = KFold(n_splits = 5, shuffle=True)

enet = ElasticNet()
lasso = Lasso()
ridge = Ridge()

enet_scores = cross_val_score(enet, X, Y, scoring = "neg_mean_squared_error",cv=cv)
lasso_scores = cross_val_score(lasso, X, Y, scoring = "neg_mean_squared_error", cv=cv)
ridge_scores = cross_val_score(ridge, X, Y, scoring = "neg_mean_squared_error", cv=cv)

print("Elastic Net CV=5 Score: ", np.average(absolute(enet_scores)))
print("Lasso CV=5 Score: ", np.average(absolute(lasso_scores)))
print("Ridge CV=5 Score: ", np.average(absolute(ridge_scores)))

Elastic Net CV=5 Score:  18.949105259589214
Lasso CV=5 Score:  20.14642424607642
Ridge CV=5 Score:  10.77977532614689

Based on the results above, Ridge regression has the lowest error; Elastic Net and Lasso are 2nd and 3rd best respectively.