In [1]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("taqdata_KO_20220301.csv")
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.dropna(inplace=True)
df.drop(10181, axis=0, inplace=True)

In [45]:
pd.read_csv("new_tqdata.csv", index_col=0)

      SYMBOL    BID  BIDSIZ    OFR  OFRSIZ  PRICE   SIZE
0         KO  62.10       4  62.15      11  62.15    1.0
1         KO  62.12       2  62.15      11  62.15    1.0
2         KO  62.09       1  62.13       1  62.10  566.0
3         KO  62.07       1  62.12       1  62.09  200.0
4         KO  62.07       1  62.13       2  62.12    1.0
...      ...    ...     ...    ...     ...    ...    ...
10176     KO  61.96     117  61.97      35  61.97    6.0
10177     KO  61.96     117  61.97      21  61.97  400.0
10178     KO  61.96     115  61.97      16  61.97  300.0
10179     KO  61.96     125  61.97      12  61.97  190.0
10180     KO  61.96     188  61.97     328  61.97  444.0

[10181 rows x 7 columns]